nafaWeb/accounts/urls.py
from django.urls import path,re_path
from . import views 
from django.contrib.auth import views as auth_views

# set app name
app_name = "accounts"

urlpatterns = [
    path("login", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register_account, name="register_account"),
    path('profile/<uid>/', views.user_profile, name="user_profile"),
    path('editProfile/<uid>/', views.edit_profile, name="edit_profile")
]

nafaWeb/event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path("event-details/<int:id>/", views.event_details, name="event_details"),
    path("add-events/", views.add_event, name="add_event"),
    path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    path("event-home/", views.event_home, name="event_home"),
    path("<eventId>/user/<userId>/add",
         views.userRegEvent, name="user_reg_event"),
    path("<eventId>/all", views.getAllUsersInEvent,
         name="get_all_users_in_event"),
    path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    path("<eventId>/user/<userId>/leave",
         views.userLeaveEvent, name="user_leave_event"),
    path('', views.email, name='email')

]

nafaWeb/grouping/urls.py
from django.urls import path
from . import views, admin
from django.contrib.auth import views as auth_views

# set app name
app_name = "grouping"

urlpatterns = [
    path("all", views.getAllGroups, name="all_groups"),
    path("create", views.createGroup, name="create_group"),
    path("update/<groupId>", views.updateGroup, name="update_group"),
    path("delete/<groupId>", views.deleteGroup, name="delete_group"),
    path("<groupId>/user/<userId>/add",
         views.userAddGroup, name="user_add_group"),
    path("<groupId>/all", views.getAllUsersInGroup,
         name="get_all_users_in_group"),
    path("all/user/<userId>", views.getUserAllGroups, name="get_user_all_groups"),
    path("<groupId>/user/<userId>/leave",
         views.userLeaveGroup, name="user_leave_group"),
    path('', views.email,
         name='email'
         )
]

nafaWeb/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    # path("event-details/<int:id>/", views.event_details, name="event_details"),
    # path("team-details/<int:id>/", views.team_details, name="team_details"),
    path("scholarship-details/<int:id>/",
         views.scholarship_details, name="scholarship_details"),
    path("campaign-details/<int:id>/",
         views.campaign_details, name="campaign_details"),
    path("membership-details/<int:id>/",
         views.membership_details, name="membership_details"),

    # path("add-events/", views.add_event, name="add_event"),
    # path("add-teams/", views.add_team, name="add_team"),
    path("add-scholarships/", views.add_scholarship, name="add_scholarship"),
    path("add-campaign/", views.add_campaign, name="add_campaign"),
    path("add-membership/", views.add_membership, name="add_membership"),

    # path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    # path("edit-team/<int:id>/", views.edit_team, name="edit_team"),
    path("edit-scholarship/<int:id>/",
         views.edit_scholarship, name="edit_scholarship"),
    path("edit-campaign/<int:id>/", views.edit_campaign, name="edit_campaign"),
    path("edit-membership/<int:id>/",
         views.edit_membership, name="edit_membership"),

    # path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    # path("delete-team/<int:id>", views.delete_team, name="delete_team"),
    path("delete-scholarship/<int:id>",
         views.delete_scholarship, name="delete_scholarship"),
    path("delete-campaign/<int:id>", views.delete_campaign, name="delete_campaign"),
    path("delete-membership/<int:id>",
         views.delete_membership, name="delete_membership"),

    # path("event-home/", views.event_home, name="event_home"),
    # path("team-home/",  views.team_home, name="team_home"),
    path("scholarship-home/",  views.scholarship_home, name="scholarship_home"),
    path("campaign-home/", views.campaign_home, name="campaign_home"),
    path("membership-home/", views.membership_home, name="membership_home"),




    # path("<eventId>/user/<userId>/add", views.userRegEvent, name="user_reg_event"),
    # path("<eventId>/all", views.getAllUsersInEvent, name="get_all_users_in_event"),
    # path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    # path("<eventId>/user/<userId>/leave", views.userLeaveEvent, name="user_leave_event"),
]

nafaWeb/nafaWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
    path("payments/", include("payments.urls")),
    path("group/", include("grouping.urls")),
    path("event/", include("event.urls")),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nafaWeb/main/models.py
import email
from email.mime import image
from pydoc import describe
from django.db import models
from django.utils import timezone

# from accounts.models import Profile

# class EventRsvp(models.Model):
#     event = models.ForeignKey(Event, related_name="event_members", on_delete=models.CASCADE, null=True, blank=True)
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField(max_length=50)
#     phone = models.IntegerField(max_length=11)
#     date = models.DateField(blank=True)
    
#     def __str__(self):
#         return self.event
    
#creating scholarship models here.
class Scholarship(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = timezone.now()
    image = models.URLField(default = None, null= True, max_length=200)

    def __str__(self):
        return self.name

#creating campaing models here. 
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = models.TimeField() 
    image = models.URLField(default = None, null= True, max_length=200)
    def __str__(self):
        return self.name
       
#creating campaing models here.
class Membership(models.Model):
    name= models.CharField(max_length=200 )
    description= models.TextField(max_length=500)
    image = models.URLField(default = None, null= True, max_length=200)
    amount = models.FloatField(null=True, blank=True)
    # validity: models.DateField()
    
    def __str__ (self):
        return self.name
    

nafaWeb/main/forms.py
from django import forms
from .models import *

        
class MembershipForm(forms.ModelForm):
    
    class Meta:
        model = Membership
        fields = ("__all__")        

class ScholarshipForm(forms.ModelForm):

    class Meta:
        model = Scholarship
        fields = ("name", "description", "date")

class CampaignForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ("name", "description", "date")


# class EventRSVPForm(forms.ModelForm):
    
#     class Meta:
#         model = EventRsvp
#         fields = ("__all__")

nafaWeb/main/views.py
from tokenize import group
from django.shortcuts import render, redirect

from .models import Scholarship, Campaign
from .forms import  MembershipForm, ScholarshipForm, CampaignForm
from HomePage.models import EditImage, EditAbout, EditOurTeam
from payments.models import Membership
from grouping.filters import *
from event.models  import *


# Create your views here.


def home(request):
    homeImageOne = EditImage.objects.get(id=1)
    homeImageTwo = EditImage.objects.get(id=2)
    homeImageThree = EditImage.objects.get(id=3)
    eventOne = Event.objects.get(id=8)
    eventTwo = Event.objects.get(id=6)
    scholarshipOne = Scholarship.objects.get(id=1)
    scholarshipTwo = Scholarship.objects.get(id=2)
    scholarshipThree = Scholarship.objects.get(id=3)
    editAbout = EditAbout.objects.get(id=1)
    editOurTeam = EditOurTeam.objects.all()

    context = {
        "homeImageOne": homeImageOne,
        "homeImageTwo": homeImageTwo,
        "homeImageThree": homeImageThree,
        "editAbout": editAbout,
        "scholarshipOne": scholarshipOne,
        "scholarshipTwo": scholarshipTwo,
        "scholarshipThree": scholarshipThree,
        "eventOne": eventOne,
        "eventTwo": eventTwo,
        "editOurTeam": editOurTeam,
        "navbar": 'home'
    }
   
    return render(request, 'main/index.html', context)




# def team_home(request):
#     teams = Team.objects.all()

#     context = {
#         "teams": teams,
#         "navbar": 'teams'
#     }
#     return render(request, 'main/singleHome/team-home.html', context)


def scholarship_home(request):
    scholarships = Scholarship.objects.all()

    context = {
        "scholarships": scholarships,
        "navbar": 'scholarships'
    }
    return render(request, 'main/singleHome/scholarship-home.html', context)


def campaign_home(request):
    campaigns = Campaign.objects.all()

    context = {
        "campaigns": campaigns,
        "navbar": 'campaigns'
    }
    return render(request, 'main/singleHome/campaign-home.html', context)


def membership_home(request):
    memberships = Membership.objects.all()
    context = {
        "memberships": memberships,
        "navbar": 'memberships'
    }
    return render(request, 'main/singleHome/membership-home.html', context)




def membership_details(request, id):
    membership = Membership.objects.get(id=id)
    context = {
        "membership": membership
    }
    return render(request, 'main/details/membership-details.html', context)



def add_membership(request):
    if request.method == "POST":
        form = MembershipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = MembershipForm()
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Add"})



def edit_membership(request, id):
    membership = Membership.objects.get(id=id)
    if request.method == "POST":
        form = MembershipForm(request.POST, instance=membership)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = MembershipForm(instance=membership)
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Edit"})




def delete_membership(request, id):
    membership = Membership.objects.get(id=id)
    membership.delete()
    return redirect("main:home")


# def team_details(request, id):
#     team = Team.objects.get(id=id)
#     context = {
#         "team": team
#     }
#     return render(request, 'main/details/team-details.html', context)


# def add_team(request):
#     if request.method == "POST":
#         form = TeamForm(request.POST or None)
#         if form.is_valid():
#             data = form.save(commit=False)
#             data.save()
#             return redirect("main:home")
#     else:
#         form = TeamForm()
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Add"})


# def edit_team(request, id):
#     team = Team.objects.get(id=id)
#     if request.method == "POST":
#         form = TeamForm(request.POST, instance=team)
#         if form.is_valid():
#             form.save()
#             return redirect("main:home")

#     else:
#         form = TeamForm(instance=team)
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Edit"})


# def delete_team(request, id):
#     team = Team.objects.get(id=id)
#     team.delete()
#     return redirect("main:home")
# def userRegEvent(request,userId,eventId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         event = Event.objects.get(id=eventId)
#         print(event.name)
#         user = Profile.objects.get(id = userId)
#         event.user.add(user)
#         return redirect("main:user_reg_event")
#     else:
#         return redirect("main:home")



# def getAllUsersInEvent(request,eventId):
#     if request.user.is_superuser:
#         event = Event.objects.get(id = eventId)
#         users = event.user.all()
#         myFilter = UserFilter(request.GET,queryset=users)
#         users = myFilter.qs
#         context = {
#             "event":event,
#             "users":users,
#             'myFilter':myFilter
#         }
#         return render(request,'eventActions/all_users_in_event.html',context)
#     else:
#         return redirect("main:home")


# def getUserAllEvents(request,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         events = Event.objects.filter(user= user)
#         myFilter = EventFilter(request.GET,queryset=events)
#         events = myFilter.qs

#         context={
#             "events":events,
#             "myFilter":myFilter,
#             "user":user
#             }
#         return render(request,'eventActions/all_events_of_user.html',context)
#     else:
#         return redirect("main:home")


# def userLeaveEvent(request,eventId,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         print(user)
#         print(user.id)
#         group = Event.objects.get(id = eventId)
#         group.user.remove(user)
#         return redirect('group:get_user_all_events' ,userId)
#     else:
#         return redirect("main:home")


def scholarship_details(request, id):
    scholarship = Scholarship.objects.get(id=id)
    context = {
        "scholarship": scholarship
    }
    return render(request, 'main/details/scholarship-details.html', context)


def add_scholarship(request):
    if request.method == "POST":
        form = ScholarshipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = ScholarshipForm()
    return render(request, 'main/addAction/add-Scholarships.html', {"form": form, "label": "Add"})


def edit_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    if request.method == "POST":
        form = ScholarshipForm(request.POST, instance=scholarship)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=scholarship)
    return render(request, 'main/addAction/add-scholarships.html', {"form": form, "label": "Edit"})


def delete_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    scholarship.delete()
    return redirect("main:home")


def campaign_details(request, id):
    campaign = Campaign.objects.get(id=id)
    context = {
        "campaign": campaign
    }
    return render(request, 'main/details/campaign-details.html', context)


def add_campaign(request):
    if request.method == "POST":
        form = CampaignForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = CampaignForm()
    return render(request, 'main/addAction/add-Campaigns.html', {"form": form, "label": "Add"})


def edit_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    if request.method == "POST":
        form = CampaignForm(request.POST, instance=campaign)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=campaign)
    return render(request, 'main/addAction/add-campaigns.html', {"form": form, "label": "Edit"})


def delete_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    campaign.delete()
    return redirect("main:home")

nafaWeb/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <style>
      .fa {
        padding: 20px;
        font-size: 10px;
        width: 35px;
        height: 50px;
        text-align: center;
        text-decoration: none;
        margin: 5px 5px;
        border-radius: 80%;
      }

      .fa:hover {
        opacity: 0.8;
      }

      .fa-facebook {
        background: #3b5998;
        color: white;
      }

      .fa-twitter {
        background: #55acee;
        color: white;
      }

      .fa-linkedin {
        background: #007bb5;
        color: white;
      }

      .fa-youtube {
        background: #bb0000;
        color: white;
      }

      .fa-instagram {
        background: #125688;
        color: white;
      }
    </style>
    <title>Neville Alumni</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">
          {% load static %}
          <img
            src=" {% static 'css/nafa-logo.png' %}"
            alt="logo"
            style="width: 50px; height: 50px"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'home' %} active {%endif%}"
                aria-current="page"
                href="{% url 'main:home' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'events' %} active {%endif%}"
                href="{% url 'event:event_home' %}"
                >Events</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'groups' %} active {%endif%}"
                href="{% url 'group:all_groups' %}"
                >Groups</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'scholarships' %} active {%endif%}"
                href="{% url 'main:scholarship_home' %}"
                >Scholarship</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'campaigns' %} active {%endif%}"
                href="{% url 'main:campaign_home' %}"
                >Campaign</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if navbar == 'memberships' %} active {%endif%}"
                href="{% url 'main:membership_home' %}"
                >Membership</a
              >
            </li>
          </ul>

          <ul class="navbar-nav me-5 mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                {{ request.user.username }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'accounts:user_profile' user.id%}"
                    >Profile</a
                  >
                </li>
                {%if request.user.is_superuser%}
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Settings</a></li>
                {% endif %}
                {%if user.membership%}
                <li><a class="dropdown-item" href="{% url 'main:membership_details' user.membership.id %}">My Subcribtions</a></li>
                {%endif%}
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'accounts:logout_user' %}"
                    >Logout</a
                  >
                </li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'accounts:register_account' %}"
                    >Register</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'accounts:login_user' %}"
                    >Login</a
                  >
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something</a>
                </li>
              </ul>
            </li>

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-grey text-muted">
      <!-- Section: Social media -->
      <section
        class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom bg-dark"
      >
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        {%load static%}
        <div>
          <!-- Add font awesome icons -->
          <a
            href="https://www.facebook.com/Neville-Alumni-and-Friends-Association-310455590523"
            class="fa fa-facebook"
            >f</a
          >
          <a href="#" class="fa fa-twitter"></a>
          <a href="#" class="fa fa-linkedin"></a>
          <a href="#" class="fa fa-youtube"></a>
          <a href="#" class="fa fa-instagram"></a>
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->

      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>
              </h6>
              <a class="navbar-brand" href="{% url 'main:home' %}">
                {% load static %}
                <img
                  src=" {% static 'css/nafa-logo.png' %}"
                  alt="logo"
                  style="width: 100px; height: 120px"
                />
              </a>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Links</h6>
              <p>
                <a href="#!" class="text-reset">About</a>
              </p>
              <p>
                <a href="{% url 'event:event_home' %}" class="text-reset"
                  >Events</a
                >
              </p>
              <p>
                <a href="{% url 'main:scholarship_home' %}" class="text-reset"
                  >Scholarship</a
                >
              </p>
              <p>
                <a href="{% url 'main:campaign_home' %}" class="text-reset"
                  >Campaign</a
                >
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p>
                <i class="fas fa-home me-3"></i>600 Forsythe Ave. Monroe, LA,
                71201
              </p>
              <p>
                <!-- <i class="fas fa-envelope me-3"></i>
                info@example.com -->
              </p>
              <p><i class="fas fa-phone me-3"></i>+ 01 318 387 5700</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->

      <!-- Copyright -->
      <div
        class="text-center p-4"
        style="background-color: rgba(0, 0, 0, 0.05)"
      >
        © {% now "Y" %} Copyright:
        <a class="text-reset fw-bold" href="https://www.nevillealumni.org/"
          >nevillealumni.org</a
        >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>