nafaWeb/event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path("event-details/<int:id>/", views.event_details, name="event_details"),
    path("add-events/", views.add_event, name="add_event"),
    path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    path("event-home/", views.event_home, name="event_home"),
    path("<eventId>/user/<userId>/add",
         views.userRegEvent, name="user_reg_event"),
    path("<eventId>/all", views.getAllUsersInEvent,
         name="get_all_users_in_event"),
    path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    path("<eventId>/user/<userId>/leave",
         views.userLeaveEvent, name="user_leave_event"),
    path('', views.email, name='email')

]

nafaWeb/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    # path("event-details/<int:id>/", views.event_details, name="event_details"),
    # path("team-details/<int:id>/", views.team_details, name="team_details"),
    path("scholarship-details/<int:id>/",
         views.scholarship_details, name="scholarship_details"),
    path("campaign-details/<int:id>/",
         views.campaign_details, name="campaign_details"),
    path("membership-details/<int:id>/",
         views.membership_details, name="membership_details"),

    # path("add-events/", views.add_event, name="add_event"),
    # path("add-teams/", views.add_team, name="add_team"),
    path("add-scholarships/", views.add_scholarship, name="add_scholarship"),
    path("add-campaign/", views.add_campaign, name="add_campaign"),
    path("add-membership/", views.add_membership, name="add_membership"),

    # path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    # path("edit-team/<int:id>/", views.edit_team, name="edit_team"),
    path("edit-scholarship/<int:id>/",
         views.edit_scholarship, name="edit_scholarship"),
    path("edit-campaign/<int:id>/", views.edit_campaign, name="edit_campaign"),
    path("edit-membership/<int:id>/",
         views.edit_membership, name="edit_membership"),

    # path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    # path("delete-team/<int:id>", views.delete_team, name="delete_team"),
    path("delete-scholarship/<int:id>",
         views.delete_scholarship, name="delete_scholarship"),
    path("delete-campaign/<int:id>", views.delete_campaign, name="delete_campaign"),
    path("delete-membership/<int:id>",
         views.delete_membership, name="delete_membership"),

    # path("event-home/", views.event_home, name="event_home"),
    # path("team-home/",  views.team_home, name="team_home"),
    path("scholarship-home/",  views.scholarship_home, name="scholarship_home"),
    path("campaign-home/", views.campaign_home, name="campaign_home"),
    path("membership-home/", views.membership_home, name="membership_home"),




    # path("<eventId>/user/<userId>/add", views.userRegEvent, name="user_reg_event"),
    # path("<eventId>/all", views.getAllUsersInEvent, name="get_all_users_in_event"),
    # path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    # path("<eventId>/user/<userId>/leave", views.userLeaveEvent, name="user_leave_event"),
]

nafaWeb/nafaWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
    path("payments/", include("payments.urls")),
    path("group/", include("grouping.urls")),
    path("event/", include("event.urls")),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nafaWeb/payments/urls.py
from django.urls import path
from . import views

app_name = "payments"

urlpatterns = [
    path("checkout/<int:id>/", views.checkout, name="checkout"),
    path("complete/", views.paymentComplete, name="complete")
]

nafaWeb/main/models.py
import email
from email.mime import image
from pydoc import describe
from django.db import models
from django.utils import timezone

# from accounts.models import Profile

# class EventRsvp(models.Model):
#     event = models.ForeignKey(Event, related_name="event_members", on_delete=models.CASCADE, null=True, blank=True)
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField(max_length=50)
#     phone = models.IntegerField(max_length=11)
#     date = models.DateField(blank=True)
    
#     def __str__(self):
#         return self.event
    
#creating scholarship models here.
class Scholarship(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = timezone.now()
    image = models.URLField(default = None, null= True, max_length=200)

    def __str__(self):
        return self.name

#creating campaing models here. 
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = models.TimeField() 
    image = models.URLField(default = None, null= True, max_length=200)
    def __str__(self):
        return self.name
       
#creating campaing models here.
class Membership(models.Model):
    name= models.CharField(max_length=200 )
    description= models.TextField(max_length=500)
    image = models.URLField(default = None, null= True, max_length=200)
    amount = models.FloatField(null=True, blank=True)
    # validity: models.DateField()
    
    def __str__ (self):
        return self.name
    

nafaWeb/main/forms.py
from django import forms
from .models import *

        
class MembershipForm(forms.ModelForm):
    
    class Meta:
        model = Membership
        fields = ("__all__")        

class ScholarshipForm(forms.ModelForm):

    class Meta:
        model = Scholarship
        fields = ("name", "description", "date")

class CampaignForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ("name", "description", "date")


# class EventRSVPForm(forms.ModelForm):
    
#     class Meta:
#         model = EventRsvp
#         fields = ("__all__")

nafaWeb/main/views.py
from tokenize import group
from django.shortcuts import render, redirect

from .models import Scholarship, Campaign
from .forms import  MembershipForm, ScholarshipForm, CampaignForm
from HomePage.models import EditImage, EditAbout, EditOurTeam
from payments.models import Membership
from grouping.filters import *
from event.models  import *


# Create your views here.


def home(request):
    homeImageOne = EditImage.objects.get(id=1)
    homeImageTwo = EditImage.objects.get(id=2)
    homeImageThree = EditImage.objects.get(id=3)
    eventOne = Event.objects.get(id=8)
    eventTwo = Event.objects.get(id=6)
    scholarshipOne = Scholarship.objects.get(id=1)
    scholarshipTwo = Scholarship.objects.get(id=2)
    scholarshipThree = Scholarship.objects.get(id=3)
    editAbout = EditAbout.objects.get(id=1)
    editOurTeam = EditOurTeam.objects.all()

    context = {
        "homeImageOne": homeImageOne,
        "homeImageTwo": homeImageTwo,
        "homeImageThree": homeImageThree,
        "editAbout": editAbout,
        "scholarshipOne": scholarshipOne,
        "scholarshipTwo": scholarshipTwo,
        "scholarshipThree": scholarshipThree,
        "eventOne": eventOne,
        "eventTwo": eventTwo,
        "editOurTeam": editOurTeam,
        "navbar": 'home'
    }
   
    return render(request, 'main/index.html', context)




# def team_home(request):
#     teams = Team.objects.all()

#     context = {
#         "teams": teams,
#         "navbar": 'teams'
#     }
#     return render(request, 'main/singleHome/team-home.html', context)


def scholarship_home(request):
    scholarships = Scholarship.objects.all()

    context = {
        "scholarships": scholarships,
        "navbar": 'scholarships'
    }
    return render(request, 'main/singleHome/scholarship-home.html', context)


def campaign_home(request):
    campaigns = Campaign.objects.all()

    context = {
        "campaigns": campaigns,
        "navbar": 'campaigns'
    }
    return render(request, 'main/singleHome/campaign-home.html', context)


def membership_home(request):
    memberships = Membership.objects.all()
    context = {
        "memberships": memberships,
        "navbar": 'memberships'
    }
    return render(request, 'main/singleHome/membership-home.html', context)




def membership_details(request, id):
    membership = Membership.objects.get(id=id)
    context = {
        "membership": membership
    }
    return render(request, 'main/details/membership-details.html', context)



def add_membership(request):
    if request.method == "POST":
        form = MembershipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = MembershipForm()
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Add"})



def edit_membership(request, id):
    membership = Membership.objects.get(id=id)
    if request.method == "POST":
        form = MembershipForm(request.POST, instance=membership)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = MembershipForm(instance=membership)
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Edit"})




def delete_membership(request, id):
    membership = Membership.objects.get(id=id)
    membership.delete()
    return redirect("main:home")


# def team_details(request, id):
#     team = Team.objects.get(id=id)
#     context = {
#         "team": team
#     }
#     return render(request, 'main/details/team-details.html', context)


# def add_team(request):
#     if request.method == "POST":
#         form = TeamForm(request.POST or None)
#         if form.is_valid():
#             data = form.save(commit=False)
#             data.save()
#             return redirect("main:home")
#     else:
#         form = TeamForm()
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Add"})


# def edit_team(request, id):
#     team = Team.objects.get(id=id)
#     if request.method == "POST":
#         form = TeamForm(request.POST, instance=team)
#         if form.is_valid():
#             form.save()
#             return redirect("main:home")

#     else:
#         form = TeamForm(instance=team)
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Edit"})


# def delete_team(request, id):
#     team = Team.objects.get(id=id)
#     team.delete()
#     return redirect("main:home")
# def userRegEvent(request,userId,eventId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         event = Event.objects.get(id=eventId)
#         print(event.name)
#         user = Profile.objects.get(id = userId)
#         event.user.add(user)
#         return redirect("main:user_reg_event")
#     else:
#         return redirect("main:home")



# def getAllUsersInEvent(request,eventId):
#     if request.user.is_superuser:
#         event = Event.objects.get(id = eventId)
#         users = event.user.all()
#         myFilter = UserFilter(request.GET,queryset=users)
#         users = myFilter.qs
#         context = {
#             "event":event,
#             "users":users,
#             'myFilter':myFilter
#         }
#         return render(request,'eventActions/all_users_in_event.html',context)
#     else:
#         return redirect("main:home")


# def getUserAllEvents(request,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         events = Event.objects.filter(user= user)
#         myFilter = EventFilter(request.GET,queryset=events)
#         events = myFilter.qs

#         context={
#             "events":events,
#             "myFilter":myFilter,
#             "user":user
#             }
#         return render(request,'eventActions/all_events_of_user.html',context)
#     else:
#         return redirect("main:home")


# def userLeaveEvent(request,eventId,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         print(user)
#         print(user.id)
#         group = Event.objects.get(id = eventId)
#         group.user.remove(user)
#         return redirect('group:get_user_all_events' ,userId)
#     else:
#         return redirect("main:home")


def scholarship_details(request, id):
    scholarship = Scholarship.objects.get(id=id)
    context = {
        "scholarship": scholarship
    }
    return render(request, 'main/details/scholarship-details.html', context)


def add_scholarship(request):
    if request.method == "POST":
        form = ScholarshipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = ScholarshipForm()
    return render(request, 'main/addAction/add-Scholarships.html', {"form": form, "label": "Add"})


def edit_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    if request.method == "POST":
        form = ScholarshipForm(request.POST, instance=scholarship)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=scholarship)
    return render(request, 'main/addAction/add-scholarships.html', {"form": form, "label": "Edit"})


def delete_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    scholarship.delete()
    return redirect("main:home")


def campaign_details(request, id):
    campaign = Campaign.objects.get(id=id)
    context = {
        "campaign": campaign
    }
    return render(request, 'main/details/campaign-details.html', context)


def add_campaign(request):
    if request.method == "POST":
        form = CampaignForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = CampaignForm()
    return render(request, 'main/addAction/add-Campaigns.html', {"form": form, "label": "Add"})


def edit_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    if request.method == "POST":
        form = CampaignForm(request.POST, instance=campaign)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=campaign)
    return render(request, 'main/addAction/add-campaigns.html', {"form": form, "label": "Edit"})


def delete_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    campaign.delete()
    return redirect("main:home")

nafaWeb/main/templates/main/details/campaign-details.html
{% extends 'main/base.html' %} {% block content %} {% load static%}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto+Slab:400,700"
/>

<link rel="stylesheet" href="{% static 'css/aboutCard.css' %}" />

<div class="row row-big-card">
  <div class="cont">
    <a href="#" class="card-link">
      <div class="card-img">
        <div
          style="
            background-image:  url('{{campaign.image}}') "
        ></div>
      </div>
      <div class="card-inner">
        <h3>{{campaign.name}}</h3>
        <h4>There's something magical about those golden hues</h4>
        <div class="inner-text">
          <p>
            {{campaign.description}}
          </p>
        </div>
        
        <span class="cta-card">
           <a href="">
          </a> 
        </span>
        <br/>
        {% if request.user.is_superuser%}
          <span class="cta-card">
            <a href="{% url 'main:edit_campaign' campaign.id %}">
              Edit
            </a>
          </span>
          <span class="cta-card">
            <a href="{% url 'main:delete_campaign' campaign.id %}">
              Delete
            </a>
          </span>
        {% endif %}
        <br/>
        
      </div>
    </a>
  </div>
</div>


{% endblock %}

nafaWeb/main/templates/main/details/event-details.html
{% extends 'main/base.html' %} {% block content %} {% load static%}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto+Slab:400,700"
/>

<link rel="stylesheet" href="{% static 'css/aboutCard.css' %}" />

<div class="row row-big-card">
  <div class="cont">
    <a href="#" class="card-link">
      <div class="card-img">
        <div
          style="
            background-image:  url('{{event.image}}') "
        ></div>
      </div>
      <div class="card-inner">
        <h3>{{event.name}}</h3>
        <h4>There's something magical about those golden hues</h4>
        <div class="inner-text">
          <p>
            {{event.description}}
          </p>
        </div>
        
        <span class="cta-card">
           <a href="">
          </a> 
        </span>
        <br/>
        {% if request.user.is_superuser%}
          <div style="display:flex;flex-direction:row">

            <a style="text-decoration:none; border: 1px solid black;border-radius:10%;padding:1.8%;color:black;background-color:gold;margin-right:1%"  href="{% url 'event:edit_event' event.id %}">
              Edit
            </a>
          </span>
          
            <a style="text-decoration:none;border:1px solid black;border-radius:10%;padding:1.8%;color:white;background-color:red" href="{% url 'event:delete_event' event.id %}">
              Delete
            </a>
          </div>
          
          <br/>
          <span >
            <a style="text-decoration:none; border: 1px solid black;border-radius:4%;padding:2%;color:white;background-color:green;margin-right:1%" href="{% url 'event:get_all_users_in_event' event.id %}">
              View all RSVPs
            </a>
        {% endif %}
        <br/>
        
      </div>
    </a>
  </div>
</div>


{% endblock %}

nafaWeb/main/templates/main/details/membership-details.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto+Slab:400,700"/>
    <link rel="stylesheet" href="{% static 'css/aboutCard.css' %}" />
    <div class="row row-big-card">
        <div class="cont">
            <a href="#" class="card-link">
                <div class="card-img">
                    <div style=" background-image:  url('{{ membership.image }}') "></div>
                </div>
                <div class="card-inner">
                    <h3>{{ membership.name }}</h3>
                    
                    <div class="inner-text">
                        <p>
                          <h4>{{membership.description}}</h4>
                        </p>
                        <h4>${{ membership.amount }}</h4>
                    </div>
                    <span class="cta-card">
                        {% if user.membership %}
                            You currently have {{ user.membership.name }}.
                            <a href="{% url 'main:membership_home' %}">Browse other Membership</a>
                        {% else %}
                            <a href="{% url 'payments:checkout' membership.id %}">Buy Now  ${{ membership.amount }}</a>
                        {% endif %}
                    </span>
                    <br />
                    {% if request.user.is_superuser %}
                        <span class="cta-card">
                            <a href="{% url 'main:edit_membership' membership.id %}">Edit</a>
                        </span>
                        <span class="cta-card">
                            <a href="{% url 'main:delete_membership' membership.id %}">Delete</a>
                        </span>
                    {% endif %}
                </div>
            </a>
        </div>
    </div>
{% endblock %}

nafaWeb/main/templates/main/details/scholarship-details.html
{% extends 'main/base.html' %} {% block content %} {% load static%}
<link rel="stylesheet" href="{% static 'css/scholarshipabout.css' %}" />

<div class="big-card container">
  <section id="main-content" class="text-center">
    <h1 style="color: gold" id="title">{{scholarship.name}}</h1>

    <div id="img-div">
      <img
        src="{{scholarship.image}}"
        alt="A Photo of Swamy Vivekananda"
        id="image"
        class="text-center"
      />
      <p id="tribute-info">{{scholarship.description}}</p>
      <a
        href="{% url 'main:scholarship_details' scholarship.id %}"
        class="btn btn-primary"
        style="margin: 50px"
      >
        Apply</a
      >
    </div>
  </section>
</div>

{% endblock %}

nafaWeb/main/templates/main/details/team-details.html
{% extends 'main/base.html' %} {% block content %} {% load static%}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto+Slab:400,700"
/>

<link rel="stylesheet" href="{% static 'css/aboutCard.css' %}" />

<div class="row row-big-card">
  <div class="cont">
    <a href="#" class="card-link">
      <div class="card-img">
        <div
          style="
            background-image:  url('{{team.image}}') "
        ></div>
      </div>
      <div class="card-inner">
        <h3>{{team.name}}</h3>
        <h4>There's something magical about those golden hues</h4>
        <div class="inner-text">
          <p>
            {{team.description}}
          </p>
        </div>
        
        <span class="cta-card">
           <a href="">
          </a> 
        </span>
        <br/>
        {% if request.user.is_superuser%}
          <span class="cta-card">
            <a href="{% url 'main:edit_team' team.id %}">
              Edit
            </a>
          </span>
          <span class="cta-card">
            <a href="{% url 'main:delete_team' team.id %}">
              Delete
            </a>
          </span>
        {%endif%}
        <br/>
        
      </div>
    </a>
  </div>
</div>


{% endblock %}