nafaWeb/accounts/urls.py
from django.urls import path,re_path
from . import views 
from django.contrib.auth import views as auth_views

# set app name
app_name = "accounts"

urlpatterns = [
    path("login", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register_account, name="register_account"),
    path('profile/<uid>/', views.user_profile, name="user_profile"),
    path('editProfile/<uid>/', views.edit_profile, name="edit_profile")
]

nafaWeb/event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path("event-details/<int:id>/", views.event_details, name="event_details"),
    path("add-events/", views.add_event, name="add_event"),
    path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    path("event-home/", views.event_home, name="event_home"),
    path("<eventId>/user/<userId>/add",
         views.userRegEvent, name="user_reg_event"),
    path("<eventId>/all", views.getAllUsersInEvent,
         name="get_all_users_in_event"),
    path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    path("<eventId>/user/<userId>/leave",
         views.userLeaveEvent, name="user_leave_event"),
    path('', views.email, name='email')

]

nafaWeb/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    # path("event-details/<int:id>/", views.event_details, name="event_details"),
    # path("team-details/<int:id>/", views.team_details, name="team_details"),
    path("scholarship-details/<int:id>/",
         views.scholarship_details, name="scholarship_details"),
    path("campaign-details/<int:id>/",
         views.campaign_details, name="campaign_details"),
    path("membership-details/<int:id>/",
         views.membership_details, name="membership_details"),

    # path("add-events/", views.add_event, name="add_event"),
    # path("add-teams/", views.add_team, name="add_team"),
    path("add-scholarships/", views.add_scholarship, name="add_scholarship"),
    path("add-campaign/", views.add_campaign, name="add_campaign"),
    path("add-membership/", views.add_membership, name="add_membership"),

    # path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    # path("edit-team/<int:id>/", views.edit_team, name="edit_team"),
    path("edit-scholarship/<int:id>/",
         views.edit_scholarship, name="edit_scholarship"),
    path("edit-campaign/<int:id>/", views.edit_campaign, name="edit_campaign"),
    path("edit-membership/<int:id>/",
         views.edit_membership, name="edit_membership"),

    # path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    # path("delete-team/<int:id>", views.delete_team, name="delete_team"),
    path("delete-scholarship/<int:id>",
         views.delete_scholarship, name="delete_scholarship"),
    path("delete-campaign/<int:id>", views.delete_campaign, name="delete_campaign"),
    path("delete-membership/<int:id>",
         views.delete_membership, name="delete_membership"),

    # path("event-home/", views.event_home, name="event_home"),
    # path("team-home/",  views.team_home, name="team_home"),
    path("scholarship-home/",  views.scholarship_home, name="scholarship_home"),
    path("campaign-home/", views.campaign_home, name="campaign_home"),
    path("membership-home/", views.membership_home, name="membership_home"),




    # path("<eventId>/user/<userId>/add", views.userRegEvent, name="user_reg_event"),
    # path("<eventId>/all", views.getAllUsersInEvent, name="get_all_users_in_event"),
    # path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    # path("<eventId>/user/<userId>/leave", views.userLeaveEvent, name="user_leave_event"),
]

nafaWeb/nafaWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
    path("payments/", include("payments.urls")),
    path("group/", include("grouping.urls")),
    path("event/", include("event.urls")),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nafaWeb/main/models.py
import email
from email.mime import image
from pydoc import describe
from django.db import models
from django.utils import timezone

# from accounts.models import Profile

# class EventRsvp(models.Model):
#     event = models.ForeignKey(Event, related_name="event_members", on_delete=models.CASCADE, null=True, blank=True)
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField(max_length=50)
#     phone = models.IntegerField(max_length=11)
#     date = models.DateField(blank=True)
    
#     def __str__(self):
#         return self.event
    
#creating scholarship models here.
class Scholarship(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = timezone.now()
    image = models.URLField(default = None, null= True, max_length=200)

    def __str__(self):
        return self.name

#creating campaing models here. 
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2500)
    amount = models.DecimalField(max_digits = 50000, decimal_places= 2, default = 0.0)
    date = models.DateField()
    time = models.TimeField() 
    image = models.URLField(default = None, null= True, max_length=200)
    def __str__(self):
        return self.name
       
#creating campaing models here.
class Membership(models.Model):
    name= models.CharField(max_length=200 )
    description= models.TextField(max_length=500)
    image = models.URLField(default = None, null= True, max_length=200)
    amount = models.FloatField(null=True, blank=True)
    # validity: models.DateField()
    
    def __str__ (self):
        return self.name
    

nafaWeb/main/forms.py
from django import forms
from .models import *

        
class MembershipForm(forms.ModelForm):
    
    class Meta:
        model = Membership
        fields = ("__all__")        

class ScholarshipForm(forms.ModelForm):

    class Meta:
        model = Scholarship
        fields = ("name", "description", "date")

class CampaignForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ("name", "description", "date")


# class EventRSVPForm(forms.ModelForm):
    
#     class Meta:
#         model = EventRsvp
#         fields = ("__all__")

nafaWeb/main/views.py
from tokenize import group
from django.shortcuts import render, redirect

from .models import Scholarship, Campaign
from .forms import  MembershipForm, ScholarshipForm, CampaignForm
from HomePage.models import EditImage, EditAbout, EditOurTeam
from payments.models import Membership
from grouping.filters import *
from event.models  import *


# Create your views here.


def home(request):
    homeImageOne = EditImage.objects.get(id=1)
    homeImageTwo = EditImage.objects.get(id=2)
    homeImageThree = EditImage.objects.get(id=3)
    eventOne = Event.objects.get(id=8)
    eventTwo = Event.objects.get(id=6)
    scholarshipOne = Scholarship.objects.get(id=1)
    scholarshipTwo = Scholarship.objects.get(id=2)
    scholarshipThree = Scholarship.objects.get(id=3)
    editAbout = EditAbout.objects.get(id=1)
    editOurTeam = EditOurTeam.objects.all()

    context = {
        "homeImageOne": homeImageOne,
        "homeImageTwo": homeImageTwo,
        "homeImageThree": homeImageThree,
        "editAbout": editAbout,
        "scholarshipOne": scholarshipOne,
        "scholarshipTwo": scholarshipTwo,
        "scholarshipThree": scholarshipThree,
        "eventOne": eventOne,
        "eventTwo": eventTwo,
        "editOurTeam": editOurTeam,
        "navbar": 'home'
    }
   
    return render(request, 'main/index.html', context)




# def team_home(request):
#     teams = Team.objects.all()

#     context = {
#         "teams": teams,
#         "navbar": 'teams'
#     }
#     return render(request, 'main/singleHome/team-home.html', context)


def scholarship_home(request):
    scholarships = Scholarship.objects.all()

    context = {
        "scholarships": scholarships,
        "navbar": 'scholarships'
    }
    return render(request, 'main/singleHome/scholarship-home.html', context)


def campaign_home(request):
    campaigns = Campaign.objects.all()

    context = {
        "campaigns": campaigns,
        "navbar": 'campaigns'
    }
    return render(request, 'main/singleHome/campaign-home.html', context)


def membership_home(request):
    memberships = Membership.objects.all()
    context = {
        "memberships": memberships,
        "navbar": 'memberships'
    }
    return render(request, 'main/singleHome/membership-home.html', context)




def membership_details(request, id):
    membership = Membership.objects.get(id=id)
    context = {
        "membership": membership
    }
    return render(request, 'main/details/membership-details.html', context)



def add_membership(request):
    if request.method == "POST":
        form = MembershipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = MembershipForm()
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Add"})



def edit_membership(request, id):
    membership = Membership.objects.get(id=id)
    if request.method == "POST":
        form = MembershipForm(request.POST, instance=membership)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = MembershipForm(instance=membership)
    return render(request, 'main/addAction/add-membership.html', {"form": form, "label": "Edit"})




def delete_membership(request, id):
    membership = Membership.objects.get(id=id)
    membership.delete()
    return redirect("main:home")


# def team_details(request, id):
#     team = Team.objects.get(id=id)
#     context = {
#         "team": team
#     }
#     return render(request, 'main/details/team-details.html', context)


# def add_team(request):
#     if request.method == "POST":
#         form = TeamForm(request.POST or None)
#         if form.is_valid():
#             data = form.save(commit=False)
#             data.save()
#             return redirect("main:home")
#     else:
#         form = TeamForm()
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Add"})


# def edit_team(request, id):
#     team = Team.objects.get(id=id)
#     if request.method == "POST":
#         form = TeamForm(request.POST, instance=team)
#         if form.is_valid():
#             form.save()
#             return redirect("main:home")

#     else:
#         form = TeamForm(instance=team)
#     return render(request, 'main/addAction/add-teams.html', {"form": form,
#                                                              "label": "Edit"})


# def delete_team(request, id):
#     team = Team.objects.get(id=id)
#     team.delete()
#     return redirect("main:home")
# def userRegEvent(request,userId,eventId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         event = Event.objects.get(id=eventId)
#         print(event.name)
#         user = Profile.objects.get(id = userId)
#         event.user.add(user)
#         return redirect("main:user_reg_event")
#     else:
#         return redirect("main:home")



# def getAllUsersInEvent(request,eventId):
#     if request.user.is_superuser:
#         event = Event.objects.get(id = eventId)
#         users = event.user.all()
#         myFilter = UserFilter(request.GET,queryset=users)
#         users = myFilter.qs
#         context = {
#             "event":event,
#             "users":users,
#             'myFilter':myFilter
#         }
#         return render(request,'eventActions/all_users_in_event.html',context)
#     else:
#         return redirect("main:home")


# def getUserAllEvents(request,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         events = Event.objects.filter(user= user)
#         myFilter = EventFilter(request.GET,queryset=events)
#         events = myFilter.qs

#         context={
#             "events":events,
#             "myFilter":myFilter,
#             "user":user
#             }
#         return render(request,'eventActions/all_events_of_user.html',context)
#     else:
#         return redirect("main:home")


# def userLeaveEvent(request,eventId,userId):
#     if request.user.is_superuser or request.user.id == int(userId):
#         user = Profile.objects.get(id = userId)
#         print(user)
#         print(user.id)
#         group = Event.objects.get(id = eventId)
#         group.user.remove(user)
#         return redirect('group:get_user_all_events' ,userId)
#     else:
#         return redirect("main:home")


def scholarship_details(request, id):
    scholarship = Scholarship.objects.get(id=id)
    context = {
        "scholarship": scholarship
    }
    return render(request, 'main/details/scholarship-details.html', context)


def add_scholarship(request):
    if request.method == "POST":
        form = ScholarshipForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = ScholarshipForm()
    return render(request, 'main/addAction/add-Scholarships.html', {"form": form, "label": "Add"})


def edit_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    if request.method == "POST":
        form = ScholarshipForm(request.POST, instance=scholarship)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=scholarship)
    return render(request, 'main/addAction/add-scholarships.html', {"form": form, "label": "Edit"})


def delete_scholarship(request, id):
    scholarship = Scholarship.objects.get(id=id)
    scholarship.delete()
    return redirect("main:home")


def campaign_details(request, id):
    campaign = Campaign.objects.get(id=id)
    context = {
        "campaign": campaign
    }
    return render(request, 'main/details/campaign-details.html', context)


def add_campaign(request):
    if request.method == "POST":
        form = CampaignForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")
    else:
        form = CampaignForm()
    return render(request, 'main/addAction/add-Campaigns.html', {"form": form, "label": "Add"})


def edit_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    if request.method == "POST":
        form = CampaignForm(request.POST, instance=campaign)
        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = ScholarshipForm(instance=campaign)
    return render(request, 'main/addAction/add-campaigns.html', {"form": form, "label": "Edit"})


def delete_campaign(request, id):
    campaign = Campaign.objects.get(id=id)
    campaign.delete()
    return redirect("main:home")

nafaWeb/main/templates/main/singleHome/campaign-home.html
{% extends 'main/base.html' %} {% block content %}

<h1>Campaign</h1>
{% for campaign in campaigns %}
<a href="{% url 'main:campaign_details' campaign.id %}"> {{campaign.name}} </a>
<br />
{% endfor %}
{% if request.user.is_superuser%}
  <a href="{% url 'main:add_campaign' %}" class="btn btn-success ">
    Add Campaign</a
  >
{%endif%}
<br />

{% endblock %}

nafaWeb/main/templates/main/singleHome/event-home.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/ti-icons@0.1.2/css/themify-icons.css"/>
    <div class="events_area bg-dark">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="main_title">
                        <h2 class="mb-3 text-white">Upcoming Events</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for event in events %}
                    <div class="col-lg-6 col-md-6">
                        <div class="single_event position-relative">
                            <div class="event_thumb">
                                <img src="{{ event.image }}" width="80%" />
                            </div>
                            <div class="event_details">
                                <div class="d-flex mb-4">
                                    <div class="date">
                                        <span>{{ event.date }}</span>
                                    </div>
                                    <div class="time-location">
                                        <p>
                                            <span class="ti-time mr-2"></span> {{ event.time }}
                                    </p>
                                    <p>
                                        <span class="ti-location-pin mr-2"></span> {{ event.location
                                    }}
                                </p>
                            </div>
                        </div>
                        <p>
                            <a>{{ event.name }}</a>
                        </p>
                    <a href="{% url 'event:event_details' event.id %}"
                       class="btn btn-primary rounded-0 mt-3">View Details</a
                    >
                <a class="btn btn-warning"
                   style="color: white; height: 50px"
                   href="{% url 'event:user_reg_event' event.id request.user.id %}">Add Event</a
                >
            </div>
        </div>
<<<<<<< HEAD
      </div>
      {% endfor %}

      {% if request.user.is_superuser%}
<a href="{% url 'main:add_event' %}" class="btn btn-success"> Add Event</a>
{%endif%}
=======
>>>>>>> 10f535df7d36d1884501f3ff3fca4d14ddf021a9
    </div>
{% endfor %}
</div>
</div>
</div>
<<<<<<< HEAD
 {% endblock %}
=======
{% if request.user.is_superuser %}
    <a href="{% url 'event:add_event' %}" class="btn btn-success">Add Event</a>
{% endif %}
{% endblock %}
>>>>>>> 10f535df7d36d1884501f3ff3fca4d14ddf021a9

nafaWeb/main/templates/main/singleHome/membership-home.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/scholarship.css' %}" />
    <section class="wrapper">
        <div class="container-fostrap">
            {% if request.user.is_authenticated %}
                {% if user.membership %}
                    <h3>You are currently enrolled in {{user.membership.name}} membership</h3>
                    <div class="content">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4">
                                    <div class="card">
                                        <a class="img-card" href="">
                                            <img src= "{{ user.membership.image }}">
                                        </a>
                                        <div class="card-content">
                                            <h4 class="card-title">
                                                <a href="{% url 'main:membership_details' user.membership.id %}">{{ user.membership.name }}</a>
                                            </h4>
                                            <p class="card-description">
                                                <a >{{ user.membership.description }}</a>
                                                <a >${{ user.membership.amount }}</a>
                                            </p>
                                        </div>
                                        <div class="card-read-more">
                                            <a href="{% url 'main:membership_details' user.membership.id %}"
                                               class="btn btn-link btn-block">Proceed...</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div>
                    <h1 class="heading">Our Membership!</h1>
                </div>
                <div class="content">
                    <div class="container">
                        <div class="row">
                            {% for membership in memberships %}
                                <div class="col-xs-12 col-sm-4">
                                    <div class="card">
                                        <a class="img-card" href="">
                                            <img src= "{{ membership.image }}">
                                        </a>
                                        <div class="card-content">
                                            <h4 class="card-title">
                                                <a href="{% url 'main:membership_details' membership.id %}">{{ membership.name }}</a>
                                            </h4>
                                            <p class="card-description">
                                                <a >{{ membership.description }}</a>
                                                <a >${{ membership.amount }}</a>
                                            </p>
                                        </div>
                                        <div class="card-read-more">
                                            <a href="{% url 'main:membership_details' membership.id %}"
                                               class="btn btn-link btn-block">Proceed...</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div>
                    <h5 class="heading">
                    You have to <a href= "{% url 'accounts:register_account' %}">register</a>/<a href= "{% url 'accounts:login_user' %}">login</a> to be able to take a look at our memberships
                </h5>
            </div>
        {% endif %}
    </div>
</section>
{% if request.user.is_superuser %}
    <a href="{% url 'main:add_membership' %}" class="btn btn-success ">
    Add Membership</a
    >
{% endif %}
{% endblock %}

nafaWeb/main/templates/main/singleHome/scholarship-home.html
{% extends 'main/base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/scholarship.css' %}" />

<section class="wrapper">
  <div class="container-fostrap">
    <div>
      <h1 class="heading">Scholarships Available This Term</h1>
    </div>

    <div class="content">
      <div class="container">
        <div class="row">
          {% for scholarship in scholarships %}
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <a class="img-card" href="">
                <img src="{{scholarship.image}}" />
              </a>
              <div class="card-content">
                <h4 class="card-title">
                  <a href="{% url 'main:scholarship_details' scholarship.id %}">
                    {{scholarship.name}}
                  </a>
                </h4>
                <p class="card-description">
                  <a> {{scholarship.description}} </a>
                </p>
              </div>
              <div class="card-read-more">
                <a
                  href="{% url 'main:scholarship_details' scholarship.id %}"
                  class="btn btn-link btn-block"
                >
                  Read More
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

        {% if request.user.is_superuser%}
        <a href="{% url 'main:add_scholarship' %}" class="btn btn-success">
          Add Scholarships</a
        >
        {%endif%}
      </div>
    </div>
  </div>
</section>

{% endblock %}

nafaWeb/main/templates/main/singleHome/team-home.html
{% extends 'main/base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/team.css' %}" />
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
/>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 mt-4 mb-4">
      <h2 class="text-center">Our Expert Team</h2>
      <p class="text-center">
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry
      </p>
    </div>
  </div>

  <div class="row">
    {% for team in teams %}
    <div class="col-md-4">
      <div class="card-box text-center">
        <div class="team-pic">
          <img src="{{team.image}}" class="img-fluid" alt="Team Pic" />
        </div>
        <h4>{{team.name}}</h4>
        <hr />
        <p>
          {{team.description}}
        </p>
        <hr />
        <a href="{% url 'main:team_details' team.id %}" class="btn btn-primary">Know More</a>
      </div>
    </div>
    {%endfor%}
  </div>
</div>

{% if request.user.is_superuser%}
  <a href="{% url 'main:add_team' %}" class="btn btn-success ">
    Add Team</a
  >
{%endif%}

{% endblock %}