nafaWeb/accounts/urls.py
from django.urls import path,re_path
from . import views 
from django.contrib.auth import views as auth_views

# set app name
app_name = "accounts"

urlpatterns = [
    path("login", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register_account, name="register_account"),
    path('profile/<uid>/', views.user_profile, name="user_profile"),
    path('editProfile/<uid>/', views.edit_profile, name="edit_profile")
]

nafaWeb/grouping/urls.py
from django.urls import path
from . import views, admin
from django.contrib.auth import views as auth_views

# set app name
app_name = "grouping"

urlpatterns = [
    path("all", views.getAllGroups, name="all_groups"),
    path("create", views.createGroup, name="create_group"),
    path("update/<groupId>", views.updateGroup, name="update_group"),
    path("delete/<groupId>", views.deleteGroup, name="delete_group"),
    path("<groupId>/user/<userId>/add",
         views.userAddGroup, name="user_add_group"),
    path("<groupId>/all", views.getAllUsersInGroup,
         name="get_all_users_in_group"),
    path("all/user/<userId>", views.getUserAllGroups, name="get_user_all_groups"),
    path("<groupId>/user/<userId>/leave",
         views.userLeaveGroup, name="user_leave_group"),
    path('', views.email,
         name='email'
         )
]

nafaWeb/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    # path("event-details/<int:id>/", views.event_details, name="event_details"),
    # path("team-details/<int:id>/", views.team_details, name="team_details"),
    path("scholarship-details/<int:id>/",
         views.scholarship_details, name="scholarship_details"),
    path("campaign-details/<int:id>/",
         views.campaign_details, name="campaign_details"),
    path("membership-details/<int:id>/",
         views.membership_details, name="membership_details"),

    # path("add-events/", views.add_event, name="add_event"),
    # path("add-teams/", views.add_team, name="add_team"),
    path("add-scholarships/", views.add_scholarship, name="add_scholarship"),
    path("add-campaign/", views.add_campaign, name="add_campaign"),
    path("add-membership/", views.add_membership, name="add_membership"),

    # path("edit-event/<int:id>/", views.edit_event, name="edit_event"),
    # path("edit-team/<int:id>/", views.edit_team, name="edit_team"),
    path("edit-scholarship/<int:id>/",
         views.edit_scholarship, name="edit_scholarship"),
    path("edit-campaign/<int:id>/", views.edit_campaign, name="edit_campaign"),
    path("edit-membership/<int:id>/",
         views.edit_membership, name="edit_membership"),

    # path("delete-event/<int:id>", views.delete_event, name="delete_event"),
    # path("delete-team/<int:id>", views.delete_team, name="delete_team"),
    path("delete-scholarship/<int:id>",
         views.delete_scholarship, name="delete_scholarship"),
    path("delete-campaign/<int:id>", views.delete_campaign, name="delete_campaign"),
    path("delete-membership/<int:id>",
         views.delete_membership, name="delete_membership"),

    # path("event-home/", views.event_home, name="event_home"),
    # path("team-home/",  views.team_home, name="team_home"),
    path("scholarship-home/",  views.scholarship_home, name="scholarship_home"),
    path("campaign-home/", views.campaign_home, name="campaign_home"),
    path("membership-home/", views.membership_home, name="membership_home"),




    # path("<eventId>/user/<userId>/add", views.userRegEvent, name="user_reg_event"),
    # path("<eventId>/all", views.getAllUsersInEvent, name="get_all_users_in_event"),
    # path("all/user/<userId>", views.getUserAllEvents, name="get_user_all_events"),
    # path("<eventId>/user/<userId>/leave", views.userLeaveEvent, name="user_leave_event"),
]

nafaWeb/nafaWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
    path("payments/", include("payments.urls")),
    path("group/", include("grouping.urls")),
    path("event/", include("event.urls")),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nafaWeb/grouping/models.py
from django.db import models
from accounts.models import *

# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=200)
    user = models.ManyToManyField(
        Profile, related_name="group_members", blank=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

nafaWeb/grouping/forms.py
from django import forms
from .models import *


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ("__all__")
        exclude = ['user']


class SendEmailForm(forms.Form):
    subject = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': ('Subject')}))
    message = forms.CharField(widget=forms.Textarea)
    users = forms.ModelMultipleChoiceField(label="To",
                                           queryset=Group.objects.all(),
                                           widget=forms.SelectMultiple())

nafaWeb/grouping/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import *
from .forms import *
from .filters import *
from django.core.mail import send_mail, BadHeaderError
from django import forms
from django.http import HttpResponse, HttpResponseRedirect


# create group
def createGroup(request):
    if request.user.is_superuser:
        groupForm = GroupForm()
        if request.method == 'POST':
            groupForm = GroupForm(request.POST)
            if groupForm.is_valid():
                groupForm.save()

            return redirect("group:all_groups")

        context = {
            "groupForm": groupForm,
            "label": "Create"
        }

        return render(request, 'grouping/addGroup.html', context)
    else:
        return redirect("main:home")

# get all groups


def getAllGroups(request):
    myGroups = []
    if request.user.is_authenticated:
        grps= Group.objects.all()
        for group in grps:
            if request.user in group.user.all():
                myGroups.append(group)
                
    groups=Group.objects.all()
    myFilter = GroupFilter(request.GET,queryset=groups)
    groups = myFilter.qs

    context={
        "groups":groups,
        "myFilter":myFilter,
        "myGroups": myGroups
        }

# update group


def updateGroup(request, groupId):
    if request.user.is_superuser:
        group = Group.objects.get(id=groupId)
        groupForm = GroupForm(instance=group)
        if request.method == 'POST':
            groupForm = GroupForm(request.POST, instance=group)
            if groupForm.is_valid():
                groupForm.save()

            return redirect("group:all_groups")

        context = {
            "groupForm": groupForm,
            "label": "Update"
        }

        return render(request, 'grouping/addGroup.html', context)
    else:
        return redirect("main:home")


# delete group
def deleteGroup(request, groupId):
    if request.user.is_superuser:
        group = Group.objects.get(id=groupId)
        group.delete()

        return redirect("group:all_groups")
    else:
        return redirect("main:home")

# add user to a group


def userAddGroup(request, userId, groupId):
    if request.user.is_superuser or request.user.id == int(userId):
        group = Group.objects.get(id=groupId)
        print(group.name)
        user = Profile.objects.get(id=userId)
        group.user.add(user)
        return redirect("group:all_groups")
    else:
        return redirect("main:home")


# get all the users in a group
def getAllUsersInGroup(request, groupId):
    if request.user.is_superuser:
        group = Group.objects.get(id=groupId)
        users = group.user.all()
        myFilter = UserFilter(request.GET, queryset=users)
        users = myFilter.qs
        context = {
            "group": group,
            "users": users,
            'myFilter': myFilter
        }
        return render(request, 'grouping/all_users_in_group.html', context)
    else:
        return redirect("main:home")

# get all groups of a user


def getUserAllGroups(request, userId):
    if request.user.is_superuser or request.user.id == int(userId):
        user = Profile.objects.get(id=userId)
        groups = Group.objects.filter(user=user)
        myFilter = GroupFilter(request.GET, queryset=groups)
        groups = myFilter.qs

        context = {
            "groups": groups,
            "myFilter": myFilter,
            "user": user
        }
        return render(request, 'grouping/all_groups_of_user.html', context)
    else:
        return redirect("main:home")


def userLeaveGroup(request, groupId, userId):
    if request.user.is_superuser or request.user.id == int(userId):
        user = Profile.objects.get(id=userId)
        print(user)
        print(user.id)
        group = Group.objects.get(id=groupId)
        group.user.remove(user)
        return redirect('group:get_user_all_groups', userId)
    else:
        return redirect("main:home")


def email(request):
    subject = request.POST.get('subject', '')
    message = request.POST.get('message', '')
    users = request.POST.get('users', '')
    users = users.replace("'", "")
    users = users.strip('][').split(', ')
    print(subject)
    print(message)
    print(users)

    if subject and message and users:
        try:
            send_mail(subject, message, 'sajinshrestha74@gmail.com',
                      users)
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/admin')
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse('Make sure all fields are entered and valid.')

nafaWeb/grouping/templates/grouping/addGroup.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static%}
{% block content %}

<div class="container">
    <form action="" method="post" style="margin: 2% 0;">{% csrf_token %} {{groupForm|crispy}}
      <br />
      <link rel="stylesheet" href="{% static 'css/main.css' %}" />
      <input
        type="submit"
        class="btn btn-primary"
        value={{label}}
      />
    </form>

  </div>

{%  endblock %}

nafaWeb/grouping/templates/grouping/all_groups_of_user.html
{% extends 'main/base.html' %} {% load crispy_forms_tags %} {% load static%} 
{% block content %}

<div style="margin: 2% 5%; text-align: center">
  <form class="filter-form" action="" method="GET">
    {{myFilter.form}}
    <button class="btn btn-primary filter-search-button" type="submit">
      Search
    </button>
  </form>

  <div>
    {% for group in groups %}

    <div
      style="
        border: 2px solid black;
        margin: 2% 8%;
        padding: 1%;
        display: flex;
        flex-direction: row;
        justify-content: space-around;
      "
    >
      <div>
        <div style="font-size: 25px; margin-bottom: 2px">{{group.name}}</div>
      </div>
      <a class="btn btn-warning" style="color: white; height: 50px"
      href="{% url 'group:user_leave_group' group.id user.id %}"
        >Leave Group</a
      >
    </div>

    {% endfor %}
  </div>
</div>

{% endblock %}

nafaWeb/grouping/templates/grouping/all_users_in_group.html
{% extends 'main/base.html' %} {% load crispy_forms_tags %} {% load static%} {%
block content %}

<div style="margin: 2% 5%; text-align: center">
  <form class="filter-form" action="" method="GET">
    {{myFilter.form}}
    <button class="btn btn-primary filter-search-button" type="submit">
      Search
    </button>
  </form>

  <div>
    {% for user in users %}

    <div
      style="
        border: 2px solid black;
        margin: 2% 8%;
        padding: 1%;
        display: flex;
        flex-direction: row;
        justify-content: space-around;
      "
    >
      <div>
        <div style="font-size: 25px; margin-bottom: 2px">{{user.username}}</div>
      </div>
      <a
        class="btn btn-warning"
        style="color: white; height: 50px"
        href="{% url 'accounts:user_profile' user.user_id %}"
        >View Profile</a
      >
    </div>

    {% endfor %}
  </div>
</div>

{% endblock %}

nafaWeb/grouping/templates/grouping/groups.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div style="margin: 2% 5%">
        <form class="filter-form"
              action=""
              method="GET"
              style="text-align: center;
                     margin: 2% 0;">
            {{ myFilter.form }}
            <button class="btn btn-primary filter-search-button" type="submit">Search</button>
        </form>
        {% if request.user.is_superuser %}
        <a href="{% url 'group:create_group' %}"
           style=" border: 1px solid black; background-color: rgb(214, 198, 55); color: white; text-decoration: none; padding: 1%; border-radius: 10%; margin:2% 0% 2% 8%; ">Create Group</a
        >
    {% endif %}
    <div style="text-align: center">
      {% if myGroups %}
      <h3>Enrolled Groups</h3>
        {%for group in myGroups%}
         
          <div style=" border: 2px solid black; margin: 2% 8%; padding: 1%; display: flex; flex-direction: row; justify-content: space-around; ">
            <div>
                <div style="font-size: 25px; margin-bottom: 2px">{{ group.name }}</div>
                <div style="font-size: 20px; margin-bottom: 2px">{{ group.description }}</div>
            </div>
            {% if request.user.is_superuser %}
            <a class="btn btn-danger"
              style="color: white;
                      height: 50px;"
              href="{% url 'group:delete_group' group.id %}">Delete Group</a
            >
            {% else %}
            <a class="btn btn-warning"
              style="color: green; height: 50px"
              href="">Enrolled</a
              {% comment %} {% url 'group:user_add_group' group.id request.user.id %} {% endcomment %}
            >
            {% endif %}
          </div>
          {%endfor%}
         {% endif %}
        <h3>Rest of the group</h3>
        {% for group in groups %}
          {% if not request.user in group.user.all %}
            
            <div style=" border: 2px solid black; margin: 2% 8%; padding: 1%; display: flex; flex-direction: row; justify-content: space-around; ">
                <div>
                    <div style="font-size: 25px; margin-bottom: 2px">{{ group.name }}</div>
                    <div style="font-size: 20px; margin-bottom: 2px">{{ group.description }}</div>
                </div>
                {% if request.user.is_superuser %}
                <a class="btn btn-danger"
                   style="color: white;
                          height: 50px;"
                   href="{% url 'group:delete_group' group.id %}">Delete Group</a
                >
                {% else %}
                <a class="btn btn-warning"
                  style="color: white; height: 50px"
                  href="{% url 'group:user_add_group' group.id request.user.id %}">Add Group</a
                >
                {% endif %}
            </div>
          
          {% endif %}
        {% endfor %}
    </div>
  </div>
{% endblock %}

nafaWeb/grouping/templates/grouping/send_email.html
{% extends "admin/base_site.html" %} {% block content %}
<form method="POST" action="{% url 'grouping:email' %}">
  {% csrf_token %}

  <div>
    <h1>Write your message here</h1>
    <br />
    <div>
      <select name="users" multiple style="display: none">
        <option value="{{ form.users.initial }}" selected>
          {{ form.users.initial }}
        </option>
      </select>
    </div>
    <div>
      <p>{{ form.subject.errors }}</p>
      <p>{{ form.subject.label_tag }}</p>
      <p>{{ form.subject }}</p>
    </div>
    <div>
      <p>{{ form.message.errors }}</p>
      <p>{{ form.message.label_tag }}</p>
      <p>{{ form.message }}</p>
    </div>
    <input type="submit" value="Send message" />
  </div>
</form>
{% endblock %}